Fix vCenter connection validation error on classy cluster manifest
Tanzu cli fails to validate vcenter connection when the config file
is a classy cluster manifest. See the following error:
Error: workload cluster configuration validation failed: vSphere config
validation failed: failed to get VC client: failed to get VSPHERE_USERNAME

There is no cluster variable which can be mapped to them so we need to
retrieve them from VSphereCluster's identityRef.