clusterclient: Add capi experimental to clusterclient scheme (#3654)
to resolve issue where `tanzu cluster get` fails because of

Error: no kind is registered for the type v1beta1.MachinePoolList in scheme "pkg/runtime/scheme.go:100"

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>